### ISSUE TITLE
Grade averages are a bit off

### ISSUE THREAD

**Issue by nitin340** [howlbits/gradedapp#8]
I think you are aware of this but the app displays 130% instead of 100% if you have all 100's in your classes.
If possible please fix this.

Thank you,
-Nitin

**Comment by geooot** [comment]
Hi,
Can you please provide screenshots so I see the issue.
Thanks,
George

**Comment by nitin340** [comment]
Yes,
![screenshot at sep 18 15-00-51](https://cloud.githubusercontent.com/assets/20330617/18618670/04258ce2-7db1-11e6-824a-5e7c37bd67e2.png)
Thank you.

**Comment by geooot** [comment]
Weird,

I do not calculate the average, I just take it straight from HAC.
Try going to the HAC website and login normally. In the classwork page, press the "Full View" button on the top right. See if the 130 shows up then

**Comment by nitin340** [comment]
HAC is offline for some odd reason right now, but when I saw my score it said 130% on it.

**Comment by nitin340** [comment]
I think it was because my teacher had made a mistake with one of the grades and it calculated it to be 130%, I'll close this issue. Thanks.
